name: Run Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2' # Use the version you need

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the version you need

      - name: Install dependencies
        run: |
          cd frontend/evidencaLetenja
          npm install

      - name: Run tests
        run: |
          cd frontend/evidencaLetenja
          npm test
        working-directory: frontend/evidencaLetenja
