name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/evidencaLetenja/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/evidencaLetenja/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install dependencies
        run: |
          cd frontend/evidencaLetenja
          npm install

      - name: Build Frontend
        run: |
          cd frontend/evidencaLetenja
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/evidencaLetenja/.svelte-kit/output
          if-no-files-found: error

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for Frontend
        run: |
          docker build -t klancnikmiha/rirs:frontend-latest -f frontend/Dockerfile frontend

      - name: Push Docker image for Frontend to Docker Hub
        run: |
          docker push klancnikmiha/rirs:frontend-latest
